services:
  - type: web
    name: natty-xmd
    env: node
    plan: free
    buildCommand: "npm install --legacy-peer-deps"
    startCommand: "node index.js"
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: NPM_CONFIG_ENGINE_STRICT
        value: "false"
